# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-15 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Twitter_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('full_name', models.CharField(max_length=200)),
                ('bio', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('joined_date', models.CharField(max_length=100)),
                ('personal_url', models.URLField()),
                ('nbTweets', models.PositiveIntegerField(default=0)),
                ('nbFollowers', models.PositiveIntegerField(default=0)),
                ('nbFollowing', models.PositiveIntegerField(default=0)),
                ('nbLikes', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
