# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-03 11:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Twitter_Tweet',
            fields=[
                ('tweet_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('media_url', models.URLField(blank=True, max_length=300)),
                ('text', models.TextField()),
                ('longitude', models.CharField(blank=True, max_length=100)),
                ('latitude', models.CharField(blank=True, max_length=100)),
                ('lang', models.CharField(blank=True, max_length=10)),
                ('favorite_count', models.PositiveIntegerField(default=0)),
                ('retweet_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.CharField(blank=True, max_length=100)),
                ('updated_at', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Twitter_User',
            fields=[
                ('username', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200)),
                ('img_url', models.URLField(blank=True, max_length=300)),
                ('bio', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('joined_at', models.CharField(max_length=100)),
                ('personal_url', models.URLField()),
                ('tweets_count', models.PositiveIntegerField(default=0)),
                ('followers_count', models.PositiveIntegerField(default=0)),
                ('following_count', models.PositiveIntegerField(default=0)),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.CharField(blank=True, max_length=100)),
                ('updated_at', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='twitter_tweet',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrapAPI.Twitter_User'),
        ),
    ]
