# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-14 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Twitter_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('Bio', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('personal_url', models.URLField(max_length=300)),
                ('nbtweets', models.PositiveIntegerField(default=0)),
                ('nbFollowers', models.PositiveIntegerField(default=0)),
                ('nbFollowing', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
