# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-02 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitter_user',
            name='username',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
