# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-03 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitter_tweet',
            name='truncated',
            field=models.BooleanField(default=False),
        ),
    ]
