# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-02 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapAPI', '0002_auto_20161202_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitter_user',
            name='created_date',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='twitter_user',
            name='img_url',
            field=models.URLField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='twitter_user',
            name='updated_date',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
